### PR TITLE
Minor cmake fixes

### PR DESCRIPTION
**Pull request by junghans**
Fix up for #107

### CODE REVIEW

**Comment by matteo-frigo** [comment]
Can you and @xantares agree on the cmake-correct way of doing things and send me a single pull request?  I have no way to know whether GNUInstallDirs is better than the other way.

**Comment by junghans** [comment]
@matteo-frigo: Sure. @xantares: please have a look and tell me what you think.

In 4fbb72ad294e2070d64a83b24f89a601d4f624c6: `FFTW3ConfigVersion.cmake` doesn't get build or install when using autotools and `@fftw3_lib@` isn't replaced. The latter seems to be fixed #109.

**Comment by junghans** [comment]
I merged the changes from #109.

**Comment by xantares** [comment]
+1 for GNUInstallDirs
 
You can add my fix for the include dir:
https://github.com/FFTW/fftw3/pull/109/commits/76427f30080e2cab3ca5047193ce8ffe6110f047

**Comment by junghans** [comment]
> You can add my fix for the include dir: 76427f3

Done

**Pull request merged**
