### PR TITLE
Build und install cmake module

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
Also see, https://gitlab.kitware.com/cmake/cmake/merge_requests/77#note_159555

**Comment by junghans** [comment]
@xantares: Did you added something like this to #103?

**Comment by matteo-frigo** [comment]
I pulled #103

**Comment by junghans** [comment]
@matteo-frigo: This PR isn't included in #103. (I just looked through it.)

**Comment by matteo-frigo** [comment]
Ack.

I pulled your patch.  Does it deserve any documentation, or does everything happen automatically?  (I.e., does cmake know by default to look into /usr/local/share/cmake/Modules or whatever?)

**Comment by junghans** [comment]
> I pulled your patch. Does it deserve any documentation, or does everything happen automatically? (I.e., does cmake know by default to look into /usr/local/share/cmake/Modules or whatever?)

Yes, everything is automatically.

I will send another PR to make FFTW's new cmake buildsystem generate the `FindFFTW3.cmake` file as well.

**Comment by xantares** [comment]
That's not the advised way of writing cmake config files, look for config mode:
https://cmake.org/cmake/help/v3.0/command/find_package.html

Basically you should instead provide a FFTW3Config.cmake that's installed into (libdir)/cmake/fftw3
This file defines FFTW3_LIBRARIES, FFTW3_INCLUDE_DIRS, version etc

**Comment by junghans** [comment]
@xantares: Yeah, but this PR was from before #103 and only meant to support project linking again fftw (build by autotools).

**Pull request merged**
